"""initial schema: all tables from PRD

Revision ID: 16bd2299cf52
Revises: 
Create Date: 2026-02-20 19:20:42.372149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16bd2299cf52'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_data', sa.JSON(), nullable=True),
    sa.Column('composite_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('aligned_layers', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('celestial_state',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('lunar_phase_angle', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('lunar_phase_name', sa.String(length=20), nullable=True),
    sa.Column('lunar_illumination', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('days_to_next_new_moon', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('days_to_next_full_moon', sa.DECIMAL(precision=6, scale=2), nullable=True),
    sa.Column('is_lunar_eclipse', sa.Boolean(), nullable=False),
    sa.Column('is_solar_eclipse', sa.Boolean(), nullable=False),
    sa.Column('mercury_retrograde', sa.Boolean(), nullable=False),
    sa.Column('venus_retrograde', sa.Boolean(), nullable=False),
    sa.Column('mars_retrograde', sa.Boolean(), nullable=False),
    sa.Column('jupiter_retrograde', sa.Boolean(), nullable=False),
    sa.Column('saturn_retrograde', sa.Boolean(), nullable=False),
    sa.Column('retrograde_count', sa.Integer(), nullable=False),
    sa.Column('sun_longitude', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('moon_longitude', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('mercury_longitude', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('venus_longitude', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('mars_longitude', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('jupiter_longitude', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('saturn_longitude', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('active_aspects', sa.JSON(), nullable=True),
    sa.Column('ingresses', sa.JSON(), nullable=True),
    sa.Column('celestial_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('confluence_scores',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('ta_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('onchain_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('celestial_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('numerology_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('political_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('composite_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('signal_strength', sa.String(length=10), nullable=True),
    sa.Column('aligned_layers', sa.JSON(), nullable=True),
    sa.Column('alignment_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol', 'timeframe')
    )
    op.create_table('custom_cycles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cycle_days', sa.Integer(), nullable=False),
    sa.Column('reference_date', sa.Date(), nullable=False),
    sa.Column('reference_event', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('miss_count', sa.Integer(), nullable=False),
    sa.Column('hit_rate', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('tolerance_days', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gematria_values',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('term', sa.String(length=100), nullable=False),
    sa.Column('english_ordinal', sa.Integer(), nullable=True),
    sa.Column('full_reduction', sa.Integer(), nullable=True),
    sa.Column('reverse_ordinal', sa.Integer(), nullable=True),
    sa.Column('reverse_reduction', sa.Integer(), nullable=True),
    sa.Column('jewish_gematria', sa.Integer(), nullable=True),
    sa.Column('english_gematria', sa.Integer(), nullable=True),
    sa.Column('digit_sum', sa.Integer(), nullable=True),
    sa.Column('is_prime', sa.Boolean(), nullable=True),
    sa.Column('associated_planet', sa.String(length=20), nullable=True),
    sa.Column('associated_element', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('term')
    )
    op.create_table('historical_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('magnitude_pct', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('price_at_event', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('duration_hours', sa.Integer(), nullable=True),
    sa.Column('days_since_previous_crash', sa.Integer(), nullable=True),
    sa.Column('days_since_previous_pump', sa.Integer(), nullable=True),
    sa.Column('days_since_previous_halving', sa.Integer(), nullable=True),
    sa.Column('lunar_phase_name', sa.String(length=20), nullable=True),
    sa.Column('mercury_retrograde', sa.Boolean(), nullable=True),
    sa.Column('active_aspects_snapshot', sa.JSON(), nullable=True),
    sa.Column('date_universal_number', sa.Integer(), nullable=True),
    sa.Column('active_cycle_alignments', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_symbol', 'historical_events', ['symbol', 'timestamp'], unique=False)
    op.create_index('idx_events_type_time', 'historical_events', ['event_type', 'timestamp'], unique=False)
    op.create_table('numerology_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('date_digit_sum', sa.Integer(), nullable=True),
    sa.Column('is_master_number', sa.Boolean(), nullable=False),
    sa.Column('master_number_value', sa.Integer(), nullable=True),
    sa.Column('universal_day_number', sa.Integer(), nullable=True),
    sa.Column('active_cycles', sa.JSON(), nullable=True),
    sa.Column('cycle_confluence_count', sa.Integer(), nullable=False),
    sa.Column('price_47_appearances', sa.JSON(), nullable=True),
    sa.Column('numerology_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('date'),
    sa.UniqueConstraint('date')
    )
    op.create_table('onchain_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange_inflow', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('exchange_outflow', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('exchange_netflow', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('whale_transactions_count', sa.Integer(), nullable=True),
    sa.Column('whale_volume_usd', sa.DECIMAL(precision=20, scale=2), nullable=True),
    sa.Column('active_addresses', sa.Integer(), nullable=True),
    sa.Column('hash_rate', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('nupl', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('mvrv_zscore', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('sopr', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('onchain_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol')
    )
    op.create_table('political_calendar',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=False),
    sa.Column('expected_volatility', sa.String(length=10), nullable=True),
    sa.Column('expected_direction', sa.String(length=10), nullable=True),
    sa.Column('crypto_relevance', sa.Integer(), nullable=False),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('actual_price_impact_pct', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('date_gematria_value', sa.Integer(), nullable=True),
    sa.Column('key_figure_gematria', sa.JSON(), nullable=True),
    sa.Column('event_title_gematria', sa.JSON(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=100), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_polcal_category', 'political_calendar', ['category', 'event_date'], unique=False)
    op.create_index('idx_polcal_date', 'political_calendar', ['event_date'], unique=False)
    op.create_index('idx_polcal_type', 'political_calendar', ['event_type', 'event_date'], unique=False)
    op.create_table('political_news',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('subcategory', sa.String(length=50), nullable=True),
    sa.Column('crypto_relevance_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('sentiment_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('urgency_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('headline_gematria', sa.JSON(), nullable=True),
    sa.Column('mention_velocity', sa.Integer(), nullable=True),
    sa.Column('mention_velocity_1h', sa.Integer(), nullable=True),
    sa.Column('mention_velocity_4h', sa.Integer(), nullable=True),
    sa.Column('peak_velocity', sa.Integer(), nullable=True),
    sa.Column('peak_velocity_time', sa.DateTime(), nullable=True),
    sa.Column('btc_price_at_publish', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('btc_price_1h_after', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('btc_price_4h_after', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('btc_price_24h_after', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('actual_impact_pct', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('political_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'source_name', 'headline')
    )
    op.create_index('idx_polnews_category', 'political_news', ['category', 'timestamp'], unique=False)
    op.create_index('idx_polnews_relevance', 'political_news', ['crypto_relevance_score', 'timestamp'], unique=False)
    op.create_table('political_signal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('hours_to_next_major_event', sa.Integer(), nullable=True),
    sa.Column('next_event_type', sa.String(length=50), nullable=True),
    sa.Column('next_event_expected_volatility', sa.String(length=10), nullable=True),
    sa.Column('upcoming_events_7d', sa.Integer(), nullable=True),
    sa.Column('upcoming_high_impact_7d', sa.Integer(), nullable=True),
    sa.Column('news_volume_1h', sa.Integer(), nullable=True),
    sa.Column('news_volume_24h', sa.Integer(), nullable=True),
    sa.Column('avg_news_sentiment_1h', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('avg_news_sentiment_24h', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('max_urgency_1h', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('dominant_narrative', sa.String(length=100), nullable=True),
    sa.Column('narrative_strength', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('narrative_direction', sa.String(length=10), nullable=True),
    sa.Column('political_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('price_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('open', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('high', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('low', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('close', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('volume', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol', 'exchange', 'timeframe')
    )
    op.create_index('idx_price_symbol_time', 'price_data', ['symbol', 'timestamp'], unique=False)
    op.create_table('sentiment_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('fear_greed_index', sa.Integer(), nullable=True),
    sa.Column('fear_greed_label', sa.String(length=20), nullable=True),
    sa.Column('social_volume', sa.Integer(), nullable=True),
    sa.Column('social_sentiment', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('social_source', sa.String(length=20), nullable=True),
    sa.Column('google_trends_score', sa.Integer(), nullable=True),
    sa.Column('sentiment_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol')
    )
    op.create_table('signal_weights',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_name', sa.String(length=50), nullable=False),
    sa.Column('ta_weight', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('onchain_weight', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('celestial_weight', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('numerology_weight', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('sentiment_weight', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('political_weight', sa.DECIMAL(precision=5, scale=4), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ta_indicators',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=5), nullable=False),
    sa.Column('rsi_14', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('rsi_7', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('macd_line', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('macd_signal', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('macd_histogram', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('stoch_k', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('stoch_d', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('sma_20', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('sma_50', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('sma_200', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('ema_12', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('ema_26', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('bb_upper', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('bb_middle', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('bb_lower', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('atr_14', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('fib_0', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('fib_236', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('fib_382', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('fib_500', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('fib_618', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('fib_786', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('fib_1000', sa.DECIMAL(precision=20, scale=8), nullable=True),
    sa.Column('ta_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp', 'symbol', 'timeframe')
    )
    op.create_table('watched_symbols',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('timeframes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watched_symbols')
    op.drop_table('ta_indicators')
    op.drop_table('signal_weights')
    op.drop_table('sentiment_data')
    op.drop_index('idx_price_symbol_time', table_name='price_data')
    op.drop_table('price_data')
    op.drop_table('political_signal')
    op.drop_index('idx_polnews_relevance', table_name='political_news')
    op.drop_index('idx_polnews_category', table_name='political_news')
    op.drop_table('political_news')
    op.drop_index('idx_polcal_type', table_name='political_calendar')
    op.drop_index('idx_polcal_date', table_name='political_calendar')
    op.drop_index('idx_polcal_category', table_name='political_calendar')
    op.drop_table('political_calendar')
    op.drop_table('onchain_metrics')
    op.drop_table('numerology_daily')
    op.drop_index('idx_events_type_time', table_name='historical_events')
    op.drop_index('idx_events_symbol', table_name='historical_events')
    op.drop_table('historical_events')
    op.drop_table('gematria_values')
    op.drop_table('custom_cycles')
    op.drop_table('confluence_scores')
    op.drop_table('celestial_state')
    op.drop_table('alerts')
    # ### end Alembic commands ###
