"""add macro liquidity layer 7 tables

Revision ID: badff7346444
Revises: 05ecd6d34fa2
Create Date: 2026-02-22 16:30:57.116739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'badff7346444'
down_revision: Union[str, Sequence[str], None] = '05ecd6d34fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carry_trade_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('usdjpy', sa.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('eurusd', sa.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('usdjpy_sma_20', sa.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('usdjpy_atr_14', sa.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('usdjpy_rsi_14', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('jpy_net_positioning', sa.Integer(), nullable=True),
    sa.Column('jpy_positioning_zscore', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('carry_stress_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index('idx_carry_ts', 'carry_trade_data', ['timestamp'], unique=False)
    op.create_table('liquidity_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('m2_supply', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('fed_balance_sheet', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('fed_funds_rate', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('treasury_general_acct', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('reverse_repo', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('net_liquidity', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index('idx_liquidity_ts', 'liquidity_data', ['timestamp'], unique=False)
    op.create_table('macro_liquidity_signal',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('liquidity_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('treasury_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('dollar_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('oil_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('carry_trade_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('macro_score', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('regime', sa.String(length=30), nullable=True),
    sa.Column('regime_confidence', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('net_liquidity', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('m2_yoy_pct', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('yield_curve_2s10s', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('dxy_value', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('vix_value', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('wti_price', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('usdjpy_value', sa.DECIMAL(precision=12, scale=6), nullable=True),
    sa.Column('carry_stress', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('sub_signals', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index('idx_macro_signal_ts', 'macro_liquidity_signal', ['timestamp'], unique=False)
    op.create_table('macro_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('dxy_index', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('vix', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index('idx_macroprices_ts', 'macro_prices', ['timestamp'], unique=False)
    op.create_table('oil_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('wti_price', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('brent_price', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('wti_brent_spread', sa.DECIMAL(precision=10, scale=4), nullable=True),
    sa.Column('crude_inventory', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('inventory_change', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index('idx_oil_ts', 'oil_data', ['timestamp'], unique=False)
    op.create_table('rate_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('dgs2', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('dgs10', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('yield_curve_2s10s', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('dfii10', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('t5yie', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.Column('cpi_yoy', sa.DECIMAL(precision=8, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_index('idx_rate_ts', 'rate_data', ['timestamp'], unique=False)
    op.add_column('confluence_scores', sa.Column('macro_score', sa.DECIMAL(precision=5, scale=4), nullable=True))
    op.add_column('signal_weights', sa.Column('macro_weight', sa.DECIMAL(precision=5, scale=4), nullable=False, server_default='0.0000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signal_weights', 'macro_weight')
    op.drop_column('confluence_scores', 'macro_score')
    op.drop_index('idx_rate_ts', table_name='rate_data')
    op.drop_table('rate_data')
    op.drop_index('idx_oil_ts', table_name='oil_data')
    op.drop_table('oil_data')
    op.drop_index('idx_macroprices_ts', table_name='macro_prices')
    op.drop_table('macro_prices')
    op.drop_index('idx_macro_signal_ts', table_name='macro_liquidity_signal')
    op.drop_table('macro_liquidity_signal')
    op.drop_index('idx_liquidity_ts', table_name='liquidity_data')
    op.drop_table('liquidity_data')
    op.drop_index('idx_carry_ts', table_name='carry_trade_data')
    op.drop_table('carry_trade_data')
    # ### end Alembic commands ###
